---

- name: 📦 packages | ensure apt list dir exists
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755
  tags:
    - config.packages

- name: 📦 Update apt cache
  become: yes
  apt:
    update_cache: yes
  tags:
    - config.packages

- name: 📦 Install additional packages
  become: yes
  apt:
    pkg:
      - gpg
      - gpg-agent
      - python3
      - python3-pip
      - rsyslog
      - update-motd
      - libssl-dev
      - libudev-dev
      - pkg-config
      - zlib1g-dev
      - llvm
      - clang
      - cmake
      - make
      - libprotobuf-dev
      - protobuf-compiler
  tags:
    - config.packages
