- name: Install go
  import_tasks: go.yaml
  tags:
    - go.install

- name: clone tpu-traffic-classifier repo
  become: true
  become_user: ubuntu
  become_method: sudo
  git:
    repo: https://github.com/rpcpool/tpu-traffic-classifier.git
    dest: /home/ubuntu/tpu-traffic-classifier
    clone: yes
    update: yes
  tags:
    - tpu-traffic-classifier.install

- name: build tpu-traffic-classifier
  become_user: ubuntu
  shell: go build -o tpu-traffic-classifier .
  args:
    chdir: /home/ubuntu/tpu-traffic-classifier
    executable: /bin/bash
  tags:
    - tpu-traffic-classifier.install

- name: copy tpu-traffic-classifier
  become: true
  copy:
    src: /home/ubuntu/tpu-traffic-classifier/tpu-traffic-classifier
    dest: /usr/local/sbin/tpu-traffic-classifier
    remote_src: true
    owner: ubuntu
    group: ubuntu
    mode: 0755
  tags:
    - tpu-traffic-classifier.install

- name: create download dir
  file:
    path: /etc/tpu-traffic-classifier
    state: directory
    owner: ubuntu
    group: ubuntu
  tags:
    - tpu-traffic-classifier.install

- name: copy tpu-traffic-classifier config
  become: true
  copy:
    src: /home/ubuntu/tpu-traffic-classifier/config.yml
    dest: /etc/tpu-traffic-classifier/config.yml
    remote_src: true
    owner: ubuntu
    group: ubuntu
    mode: 0755
  tags:
    - tpu-traffic-classifier.install

- name: delete repo
  become: true
  command: rm -rf /home/ubuntu/tpu-traffic-classifier
  tags:
    - tpu-traffic-classifier.install

# define pubkey strategy
- name: Create tpu-traffic.classifier service
  become: true
  template:
    src: tpu-traffic-classifier.service.j2
    dest: /etc/systemd/system/tpu-traffic-classifier.service
    mode: 0644
    owner: root
    group: root
  tags:
    - tpu-traffic-classifier.install

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes
  tags:
    - tpu-traffic-classifier.install

- name: Enable tpu-traffic-classifier service
  become: true
  systemd:
    name: tpu-traffic-classifier
    enabled: yes
  tags:
    - tpu-traffic-classifier.install
