- name: jito solana repository
  become: true
  become_user: solana
  git:
    repo: {{ jito_solana_repo }}
    dest: /home/solana/jito-solana
    version: tags/{{ solana_version }}-jito
    recursive: yes
    update: yes
    clone: yes


- name: build solana
  become: true
  become_user: solana
  shell: source /home/solana/.cargo/env && /mnt/solana/cargo build --release
  args:
    chdir: /home/solana/jito-solana
    executable: /bin/bash