---
- name: Install nginx deps
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - clang
    - cmake
    - make
    - libssl-dev
    - zlib1g-dev
    - libpcre3
    - libpcre3-dev
    - unzip
  tags:
    - nginx.install

- name: 🐸 Ensure group nginx exists
  ansible.builtin.group:
    name: nginx
    state: present
  tags:
    - nginx.install

- name: 🐸 Create user nginx
  user:
    name: nginx
    state: present
    create_home: yes
    shell: /bin/bash
    skeleton: /etc/skel
    force: yes
    groups:
      - nginx
      - syslog
  tags:
    - nginx.install

- name: Downloading NGINX sources
  get_url:
    url: "{{ nginx_tarball_url }}"
    dest: "/tmp/{{ nginx_version }}.tar.gz"
  register: nginx_source
  tags:
    - nginx.install

- name: Unpacking NGINX
  unarchive:
    copy: no
    dest: /tmp/
    src: "{{ nginx_source.dest }}"
  when: nginx_source.changed
  register: nginx_source_unpack
  tags:
    - nginx.install

- name: Create required Nginx dirs
  become: yes
  file:
    path: /etc/nginx
    state: directory
    owner: nginx
    mode: 0755
  tags:
    - nginx.install

- name: Configuring NGINX source with custom modules
  command: "./configure --sbin-path={{ nginx_sbin_path }} --conf-path={{ nginx_conf_path }} --error-log-path={{ nginx_error_log_path }} --http-log-path={{ nginx_http_log_path }} --with-pcre --pid-path={{ nginx_pid_path }} {{ nginx_custom_modules }}"
  args:
    chdir: "{{ nginx_install_dir }}"
  when: nginx_source_unpack
  register: nginx_configure
  tags:
    - nginx.install

- name: Installing NGINX
  become: yes
  shell: make && make install
  args:
    chdir: "{{ nginx_install_dir }}"
  when: nginx_configure
  tags:
    - nginx.install

- name: Creating NGINX conf file
  become: yes
  template:
    src: nginx.conf
    dest: "{{ nginx_conf_path }}"
    owner: nginx
    group: nginx
    mode: 0644
  tags:
    - nginx.install

- name: Add permissions to nginx directories
  file:
    dest: "{{ item }}"
    owner: nginx
    group: nginx
    recurse: yes
  loop:
    - /var/log/nginx
    - /var/run/nginx
  tags:
    - nginx.install

- name: Copy nginx.service systemd service file
  copy:
    src: "../files/nginx.service"
    dest: /etc/systemd/system/nginx.service
    mode: 0644
    owner: root
    group: root
  tags:
    - nginx.install

- name: Reload systemd
  systemd:
    daemon_reload: yes
  tags:
    - nginx.install

- name: Enable nginx service
  systemd:
    name: nginx
    enabled: yes
  tags:
    - nginx.install
